// Authentication actions
export const Authentication = {
  SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_IN_REQUEST_ERRORS: 'SIGN_IN_REQUEST_ERRORS',
  SIGN_IN_STOP: 'SIGN_IN_STOP',
  GET_USER_DATA: 'GET_USER_DATA',
  SET_USER_DATA: 'SET_USER_DATA',
  STOP_USER_DATA: 'STOP_USER_DATA',
  UPDATE_AUTH_USER: 'UPDATE_AUTH_USER',
};

// Toast messages
export const FlashMessage = {
  INFO: 'FLASH_INFO_MESSAGE',
  ERROR: 'FLASH_ERROR_MESSAGE',
  WARNING: 'FLASH_WARNING_MESSAGE',
  SUCCESS: 'FLASH_SUCCESS_MESSAGE',
  CLOSE: 'FLASH_MESSAGE_CLOSE',
};

// async queue
export const AsyncQueue = {
  PUSH: 'PUSH_TO_QUEUE',
  POP: 'POP_FROM_QUEUE',
};

export const User = {
  GET_LIST_REQUEST: 'GET_LIST_REQUEST',
  GET_LIST: 'GET_LIST',
  USER_INSERT_REQUEST: 'USER_INSERT_REQUEST',
  USER_INSERT: 'USER_INSERT',
  USER_INSERT_ERRORS: 'USER_INSERT_ERRORS',
  USER_GET_RESET_REQUEST: 'USER_GET_RESET_REQUEST',
  USER_GET_REQUEST: 'USER_GET_REQUEST',
  USER_GET: 'USER_GET',
  CLEAN_USER: 'CLEAN_USER',
  USER_STOP_REQUEST: 'USER_STOP_REQUEST',
  RESET_LIST: 'USER_RESET_LIST',
  INSERT_NEW_PAGE: 'USER_INSERT_NEW_PAGE',
  UPDATE_CURRENT_PAGE: 'USER_UPDATE_CURRENT_PAGE',
  CHANGE_PER_PAGE: 'USER_CHANGE_PER_PAGE',
};

export const LoaderDiv = {
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',
};

export const Company = {
  SET_LIST: 'COMPANY_SET_LIST',
  INSERT_REQUEST: 'INSERT_COMPANY_REQUEST',
  INSERT: 'INSERT_COMPANY',
  STOP_REQUEST: 'STOP_COMPANY_REQUEST',
  RESET_STATE: 'RESET_COMPANY_STATE',
};

export const Fuel = {
  GET_LIST_REQUEST: 'GET_FUEL_LIST_REQUEST',
  GET_LIST: 'GET_FUEL_LIST',
  CREATE_REQUEST: 'CREATE_FUEL_REQUEST',
  CREATE: 'CREATE_FUEL',
  EDIT: 'EDIT_FUEL',
  DELETE: 'DELETE_FUEL',
  STOP_REQUEST: 'STOP_FUEL_REQUEST',
};

export const ConfirmDialog = {
  OPEN: 'OPEN_CONFIRM_DIALOG',
  CLOSE: 'CLOSE_CONFIRM_DIALOG',
};

export const Recharge = {
  SET_LIST: 'RECHARGE_SET_LIST',
  INSERT: 'RECHARGE_INSERT_LIST',
  INSERT_NEW_PAGE: 'RECHARGE_INSERT_NEW_PAGE',
  CHANGE_PER_PAGE: 'RECHARGE_CHANGE_PER_PAGE',
  UPDATE_CURRENT_PAGE: 'RECHARGE_UPDATE_CURRENT_PAGE',
  RESET_LIST: 'RECHARGE_RESET_LIST',
};

export const Dashboard = {
  SET_STATISTICS: 'DASHBOARD_SET_STATISTICS',
  ADD_EARNINGS: 'DASHBOARD_ADD_EARNINGS',
};
